"""Correctly read ROM at proper offsets. Fixed bank = $C000-$FFFF.
   Offset within fixed bank = CPU_addr - $C000.
   PRG ROM offset = $7C000 + (CPU_addr - $C000).
   File offset = 16 + PRG_offset."""

import os, struct

ROM = "exidy.nes"
TRACE = r"C:\Users\membl\OneDrive\Documents\Mesen2\Debugger\exidy.txt"

with open(ROM, "rb") as f:
    rom = f.read()

prg = rom[16:]  # Skip iNES header
prg_size = len(prg)
print(f"PRG ROM size: {prg_size} bytes ({prg_size//1024}KB)")
print(f"Number of 16KB banks: {prg_size // 16384}")

# Fixed bank (last 16KB) 
FIXED_BANK_PRG = prg_size - 16384  # $7C000 for 512KB
fixed = prg[FIXED_BANK_PRG:]
print(f"Fixed bank PRG offset: ${FIXED_BANK_PRG:05X}")

def cpu_to_fixed_offset(cpu_addr):
    """Convert CPU $C000-$FFFF to offset within fixed bank"""
    return cpu_addr - 0xC000

def read_fixed(cpu_addr, length=16):
    off = cpu_to_fixed_offset(cpu_addr)
    return fixed[off:off+length]

# Check key addresses  
print("\n=== $DCF8 (_setup_flash_pc_tables per label map) ===")
b = read_fixed(0xDCF8, 32)
print(f"Hex: {b.hex(' ')}")

print("\n=== $DE39 (_ir_emit_direct_branch_placeholder per label map) ===")
b = read_fixed(0xDE39, 32)
print(f"Hex: {b.hex(' ')}")

print("\n=== $DD1B (where old trampoline's JSR $843E was) ===")
b = read_fixed(0xDD1B, 32)
print(f"Hex: {b.hex(' ')}")

# Let's also check: what does the Mesen label P:5CF8 mean?
# For Mesen NES labels, P: is absolute PRG ROM offset
# P:5CF8 as PRG offset $5CF8:
print(f"\n=== PRG offset $5CF8 (Mesen label P:5CF8) ===")
print(f"Hex: {prg[0x5CF8:0x5CF8+32].hex(' ')}")

# P:5E39 as PRG offset $5E39:
print(f"\n=== PRG offset $5E39 (Mesen label P:5E39) ===")
print(f"Hex: {prg[0x5E39:0x5E39+32].hex(' ')}")

# Verify: do the bytes at PRG $5E39 match what's at fixed bank offset $1E39?
fb_off = cpu_to_fixed_offset(0xDE39)
print(f"\n=== Fixed bank offset $1E39 (CPU $DE39) ===")
print(f"Hex: {fixed[fb_off:fb_off+32].hex(' ')}")

# Compare: are they the same? (For 512KB ROM, bank 1 != bank 31)
match = prg[0x5E39:0x5E39+32] == fixed[fb_off:fb_off+32]
print(f"PRG $5E39 == Fixed bank $DE39? {match}")

# So which one does Mesen actually use?
# For NES mapper 30, fixed bank maps to $C000-$FFFF
# The CPU sees the LAST 16KB of PRG at $C000-$FFFF
# Mesen label P:5CF8 is PRG offset $5CF8 which is in bank 1
# But the fixed bank (bank 31) PRG offset is $7C000+
# So P:5CF8 is in bank 1, NOT in the fixed bank!
#
# This means our label file is WRONG or Mesen interprets it differently.
# Let me check if the P: address wraps around or if the mlb was generated for
# a smaller ROM size.

# Actually, maybe the labels were generated by convertlabels.py from linker output
# and the linker uses a 24KB address space ($8000-$DFFF = 24KB for one switchable + fixed bank)
# Let me check convertlabels.py

# For now, let's verify: what is at PRG $5E39?
# Bank = $5E39 / $4000 = 1.4936... = bank 1
# Offset in bank 1 = $5E39 - $4000 = $1E39
# This is the same relative offset as $DE39 in the fixed bank ($DE39 - $C000 = $1E39)
# Maybe vbcc duplicates the fixed bank content into every bank's position?

# Check if the bytes at bank 1 offset $1E39 match fixed bank offset $1E39
bank1_start = 1 * 16384  # $4000
bank1_bytes = prg[bank1_start + 0x1E39:bank1_start + 0x1E39 + 32]
print(f"\n=== Bank 1 at offset $1E39 ===")
print(f"Hex: {bank1_bytes.hex(' ')}")
print(f"Bank 1 matches fixed bank? {bank1_bytes == fixed[fb_off:fb_off+32]}")

# Actually check if ALL banks have the same content at offset $1CF8-$1FFF
# (This would be the case if $DC00-$DFFF is "fixed" and replicated)
# vbcc for mapper 30 might use a 24KB code space:
#   $8000-$BFFF: 16KB switchable bank
#   $C000-$DFFF: 8KB? No that's odd.
#
# Let me check the linker script or config

# Actually, the simplest answer: Mesen label format P:XXXX for NES uses
# PRG ROM offset, and for mapper 30 with 512KB PRG, the offset is absolute.
# P:5CF8 = PRG[$5CF8] which is in bank 1.
# But our code at CPU $DCF8 is in the fixed bank (bank 31), at PRG[$7DCF8].
# So either:
#   1. The label file addresses are wrong
#   2. Or Mesen uses relative within 32KB (bank_pair addressing)

# Let me check: P:5CF8 mod $4000 = $1CF8. $C000+$1CF8 = $DCF8. 
# So Mesen might use the lower bits to map to $C000 range.
# P:5CF8 → bit 14 set → maps to $C000 + $1CF8 = $DCF8
# P:5E39 → bit 14 set → maps to $C000 + $1E39 = $DE39
# Bits 15+ indicate which bank. $5CF8 >> 14 = 1, but for fixed bank this doesn't matter.
# Maybe Mesen treats P:4000-7FFF as the "fixed bank" range?

# Let me look at bank 2 labels to confirm:
print("\n=== Labels in bank 2 region (P:8000-BFFF) ===")
with open("exidy.mlb", "r") as f:
    for line in f:
        line = line.strip()
        if line.startswith("P:"):
            parts = line.split(":")
            if len(parts) >= 3:
                try:
                    addr = int(parts[1], 16)
                    if 0x8000 <= addr <= 0x8100:
                        print(f"  {line}")
                except:
                    pass

# And bank 0 labels
print("\n=== Labels in bank 0 region (P:0000-3FFF) ===")
with open("exidy.mlb", "r") as f:
    count = 0
    for line in f:
        line = line.strip()
        if line.startswith("P:"):
            parts = line.split(":")
            if len(parts) >= 3:
                try:
                    addr = int(parts[1], 16)
                    if addr <= 0x0100:
                        print(f"  {line}")
                        count += 1
                except:
                    pass
    if count == 0:
        print("  (none)")

# Now disassemble the ACTUAL bytes at fixed bank $DCF8 ($1CF8 offset)
print("\n=== CORRECT disassembly at $DCF8 (offset $1CF8 in fixed bank) ===")
data = fixed[0x1CF8:0x1CF8+80]
print(f"Raw bytes: {data[:32].hex(' ')}")

# Simple 6502 disassembler
OPCODES = {
    0x00: ("BRK", 1), 0x01: ("ORA (zp,X)", 2), 0x05: ("ORA zp", 2),
    0x06: ("ASL zp", 2), 0x08: ("PHP", 1), 0x09: ("ORA #imm", 2),
    0x0A: ("ASL A", 1), 0x10: ("BPL rel", 2), 0x18: ("CLC", 1),
    0x20: ("JSR abs", 3), 0x24: ("BIT zp", 2), 0x25: ("AND zp", 2),
    0x26: ("ROL zp", 2), 0x28: ("PLP", 1), 0x29: ("AND #imm", 2),
    0x2A: ("ROL A", 1), 0x2C: ("BIT abs", 3), 0x30: ("BMI rel", 2),
    0x38: ("SEC", 1), 0x40: ("RTI", 1), 0x45: ("EOR zp", 2),
    0x46: ("LSR zp", 2), 0x48: ("PHA", 1), 0x49: ("EOR #imm", 2),
    0x4A: ("LSR A", 1), 0x4C: ("JMP abs", 3), 0x50: ("BVC rel", 2),
    0x60: ("RTS", 1), 0x65: ("ADC zp", 2), 0x66: ("ROR zp", 2),
    0x68: ("PLA", 1), 0x69: ("ADC #imm", 2), 0x6A: ("ROR A", 1),
    0x6C: ("JMP (abs)", 3), 0x78: ("SEI", 1), 0x81: ("STA (zp,X)", 2),
    0x84: ("STY zp", 2), 0x85: ("STA zp", 2), 0x86: ("STX zp", 2),
    0x88: ("DEY", 1), 0x8A: ("TXA", 1), 0x8C: ("STY abs", 3),
    0x8D: ("STA abs", 3), 0x8E: ("STX abs", 3), 0x90: ("BCC rel", 2),
    0x91: ("STA (zp),Y", 2), 0x94: ("STY zp,X", 2), 0x95: ("STA zp,X", 2),
    0x96: ("STX zp,Y", 2), 0x98: ("TYA", 1), 0x99: ("STA abs,Y", 3),
    0x9A: ("TXS", 1), 0x9D: ("STA abs,X", 3), 0xA0: ("LDY #imm", 2),
    0xA2: ("LDX #imm", 2), 0xA4: ("LDY zp", 2), 0xA5: ("LDA zp", 2),
    0xA6: ("LDX zp", 2), 0xA8: ("TAY", 1), 0xA9: ("LDA #imm", 2),
    0xAA: ("TAX", 1), 0xAC: ("LDY abs", 3), 0xAD: ("LDA abs", 3),
    0xAE: ("LDX abs", 3), 0xB0: ("BCS rel", 2), 0xB1: ("LDA (zp),Y", 2),
    0xB5: ("LDA zp,X", 2), 0xB9: ("LDA abs,Y", 3), 0xBD: ("LDA abs,X", 3),
    0xC0: ("CPY #imm", 2), 0xC4: ("CPY zp", 2), 0xC5: ("CMP zp", 2),
    0xC6: ("DEC zp", 2), 0xC8: ("INY", 1), 0xC9: ("CMP #imm", 2),
    0xCA: ("DEX", 1), 0xD0: ("BNE rel", 2), 0xD5: ("CMP zp,X", 2),
    0xD8: ("CLD", 1), 0xE0: ("CPX #imm", 2), 0xE4: ("CPX zp", 2),
    0xE5: ("SBC zp", 2), 0xE6: ("INC zp", 2), 0xE8: ("INX", 1),
    0xE9: ("SBC #imm", 2), 0xEA: ("NOP", 1), 0xF0: ("BEQ rel", 2),
    0xF6: ("INC zp,X", 2), 0xF8: ("SED", 1),
}

def disasm(data, base_addr, count=30):
    i = 0
    lines = 0
    while i < len(data) and lines < count:
        b = data[i]
        cpu = base_addr + i
        if b in OPCODES:
            name, size = OPCODES[b]
            if size == 1:
                print(f"  ${cpu:04X}: {name}")
            elif size == 2:
                if i+1 < len(data):
                    operand = data[i+1]
                    if "rel" in name:
                        target = cpu + 2 + (operand if operand < 128 else operand - 256)
                        print(f"  ${cpu:04X}: {name.split()[0]} ${target:04X}  (${operand:02X})")
                    else:
                        n = name.replace("zp", f"${operand:02X}").replace("imm", f"${operand:02X}")
                        print(f"  ${cpu:04X}: {n}")
                else:
                    print(f"  ${cpu:04X}: {name} ??")
            elif size == 3:
                if i+2 < len(data):
                    lo, hi = data[i+1], data[i+2]
                    addr16 = lo | (hi << 8)
                    n = name.replace("abs", f"${addr16:04X}")
                    print(f"  ${cpu:04X}: {n}")
                else:
                    print(f"  ${cpu:04X}: {name} ????")
            i += size
        else:
            print(f"  ${cpu:04X}: .db ${b:02X}  (unknown opcode)")
            i += 1
        lines += 1

disasm(data, 0xDCF8, 40)

# Also disassemble $DE39
print("\n=== CORRECT disassembly at $DE39 (our ir_emit function) ===")
data2 = fixed[0x1E39:0x1E39+80]
print(f"Raw bytes: {data2[:32].hex(' ')}")
disasm(data2, 0xDE39, 40)

# Find JSR $843E in the fixed bank
print("\n=== Searching for JSR $843E (20 3E 84) in fixed bank ===")
pattern = bytes([0x20, 0x3E, 0x84])
pos = 0
while True:
    pos = fixed.find(pattern, pos)
    if pos == -1:
        break
    cpu = 0xC000 + pos
    print(f"  Found at fixed bank offset ${pos:04X} (CPU ${cpu:04X})")
    # Show context
    start = max(0, pos-3)
    print(f"    Context: {fixed[start:pos+6].hex(' ')}")
    pos += 1

# Also search for JSR $DE39 in the fixed bank
print("\n=== Searching for JSR $DE39 (20 39 DE) in fixed bank ===")
pattern2 = bytes([0x20, 0x39, 0xDE])
pos = 0
while True:
    pos = fixed.find(pattern2, pos)
    if pos == -1:
        break
    cpu = 0xC000 + pos
    print(f"  Found at fixed bank offset ${pos:04X} (CPU ${cpu:04X})")
    pos += 1
