-- hit_rate.lua  —  Mesen 2 Lua script
-- Real-time OSD: rolling hit% of the last 128 dispatch_on_pc outcomes.
--
-- "Hit"  = dispatch_on_pc found compiled native code and executed it
-- "Miss" = dispatch_on_pc fell back to C for interpret or recompile
--
-- Addresses are resolved automatically from the .mlb debug label files
-- generated by the build (nes_dk.mlb / exidy.mlb).  No manual updates
-- needed after rebuilding.

-- ── .mlb address resolver ────────────────────────────────────────────
-- Parses a Mesen .mlb file and returns the CPU address for a label.
-- .mlb format:  R:XXXX:name  (ZP/RAM, addr = XXXX)
--               S:XXXX:name  (SRAM,   addr = XXXX + $6000)
--               W:XXXX:name  (WRAM,   addr = XXXX + $6000)
--               P:XXXX:name  (PRG,    addr = XXXX + $8000)

local SCRIPT_DIR = debug.getinfo(1, "S").source:match("@?(.*[\\/])")  or ""

local function find_addr_in_mlb(filename, label)
    local f = io.open(SCRIPT_DIR .. filename, "r")
    if not f then return nil end
    for line in f:lines() do
        local prefix, hex, name = line:match("^(%a):(%x+):(.+)$")
        if name == label then
            f:close()
            local addr = tonumber(hex, 16)
            if prefix == "S" or prefix == "W" then return addr + 0x6000
            elseif prefix == "P"              then return addr + 0x8000
            else                                   return addr
            end
        end
    end
    f:close()
    return nil
end

-- Try the loaded ROM's .mlb first by checking which one has valid data,
-- then fall back to the other.
local MLB_FILES = { "nes_dk.mlb", "exidy.mlb" }

local function resolve(label)
    for _, mlb in ipairs(MLB_FILES) do
        local addr = find_addr_in_mlb(mlb, label)
        if addr then return addr, mlb end
    end
    return nil, nil
end

local DISPATCH_RETURN, mlb1 = resolve("_flash_dispatch_return_no_regs")
local NOT_RECOMPILED,  mlb2 = resolve("not_recompiled")

if not DISPATCH_RETURN or not NOT_RECOMPILED then
    emu.displayMessage("HitRate", "ERROR: could not find addresses in .mlb files")
    emu.log("[hit_rate] Failed to resolve dispatch addresses from .mlb files")
    return
end

-- Verify: the loaded ROM should have the right code at these addresses.
-- _flash_dispatch_return_no_regs starts with PLA ($68).
-- not_recompiled starts with BEQ ($F0).
local MEM = emu.memType.nesDebug
local ok = true
if emu.read(DISPATCH_RETURN, MEM) ~= 0x68 then  -- PLA
    -- Try the other .mlb
    for _, mlb in ipairs(MLB_FILES) do
        if mlb ~= mlb1 then
            local alt = find_addr_in_mlb(mlb, "_flash_dispatch_return_no_regs")
            if alt and emu.read(alt, MEM) == 0x68 then
                DISPATCH_RETURN = alt
                NOT_RECOMPILED  = find_addr_in_mlb(mlb, "not_recompiled") or NOT_RECOMPILED
                mlb1 = mlb
                break
            end
        end
    end
    if emu.read(DISPATCH_RETURN, MEM) ~= 0x68 then
        emu.displayMessage("HitRate", "WARN: dispatch opcode mismatch — addresses may be stale")
        emu.log(string.format("[hit_rate] Expected PLA($68) at $%04X, got $%02X",
            DISPATCH_RETURN, emu.read(DISPATCH_RETURN, MEM)))
    end
end

emu.log(string.format("[hit_rate] Using %s: dispatch=$%04X  not_recompiled=$%04X",
    mlb1 or "?", DISPATCH_RETURN, NOT_RECOMPILED))

-- ── Ring buffer of last N dispatch outcomes ──────────────────────────
local RING = 128
local buf = {}
for i = 1, RING do buf[i] = 0 end   -- 0=empty, 1=hit, 2=miss
local pos    = 1
local hits   = 0
local filled = 0

local function record(kind)
    if buf[pos] == 1 then hits = hits - 1 end   -- evict old hit
    buf[pos] = kind
    if kind == 1 then hits = hits + 1 end
    pos = pos % RING + 1
    if filled < RING then filled = filled + 1 end
end

-- ── Exec callbacks ───────────────────────────────────────────────────
-- Hit: _flash_dispatch_return falls through to _flash_dispatch_return_no_regs,
-- so one hook at the common address catches both entry points.
emu.addMemoryCallback(function() record(1) end,
    emu.callbackType.exec, DISPATCH_RETURN, DISPATCH_RETURN)

-- Miss: dispatch_on_pc branches to not_recompiled for all non-compiled PCs
-- ($00=uninitialized, bit7=not compiled, INTERPRETED-only).
emu.addMemoryCallback(function() record(2) end,
    emu.callbackType.exec, NOT_RECOMPILED, NOT_RECOMPILED)

-- ── OSD overlay ──────────────────────────────────────────────────────
local GREEN  = 0x00FF00
local YELLOW = 0xFFFF00
local RED    = 0xFF4040
local BG     = 0x000020
local GREY   = 0x303030
local BORDER = 0x808080

emu.addEventCallback(function()
    if filled == 0 then return end

    local pct = hits * 100 / filled
    local col = GREEN
    if pct < 90 then col = YELLOW end
    if pct < 70 then col = RED end

    -- Small bar (64px wide)
    local bx, by, bw, bh = 2, 214, 64, 5
    local fw = math.floor(pct * bw / 100)
    emu.drawRectangle(bx, by, bw, bh, GREY, true)
    emu.drawRectangle(bx, by, fw, bh, col, true)
    emu.drawRectangle(bx, by, bw, bh, BORDER, false)

    -- Text
    emu.drawString(2, 221, string.format("Hit:%d/%d %.0f%%", hits, filled, pct), col, BG)

end, emu.eventType.endFrame)

emu.displayMessage("HitRate", string.format("Tracking last %d dispatches (from %s)", RING, mlb1 or "?"))
